spring:
  # 数据库
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://118.178.194.35:3306/community?useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 1175450568Xu!
      initial-size: 10
      max-active: 60
      min-idle: 5
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

# mybatis plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  port: 7001

jwt:
  jwtKey: Community
  jwtIssuer: Chavy
security:
  enable-session: false
  expire: 7200000